In [1]:
!pip install torch

In [3]:
import torch
# random pytorch tensor: float32, size=1000
tensor_fp32 = torch.rand(1000, dtype = torch.float32)
print(tensor_fp32)

tensor([0.3615, 0.8084, 0.0847, 0.3425, 0.2880, 0.9754, 0.2842, 0.6910, 0.8312,
        0.0721, 0.0167, 0.0331, 0.0136, 0.3273, 0.0077, 0.4918, 0.2129, 0.1961,
        0.4500, 0.2020, 0.1852, 0.9319, 0.7452, 0.5939, 0.6367, 0.4295, 0.1187,
        0.2485, 0.7731, 0.7379, 0.0569, 0.6000, 0.3470, 0.5869, 0.1001, 0.2041,
        0.1564, 0.2586, 0.1482, 0.4421, 0.7338, 0.1332, 0.2049, 0.7458, 0.6129,
        0.3862, 0.6282, 0.6222, 0.4407, 0.4792, 0.5492, 0.2975, 0.3656, 0.3497,
        0.0582, 0.5363, 0.5675, 0.3777, 0.7766, 0.2209, 0.8537, 0.7276, 0.9076,
        0.6764, 0.7823, 0.8843, 0.6332, 0.0980, 0.1483, 0.9160, 0.9865, 0.0744,
        0.5226, 0.1962, 0.2830, 0.9156, 0.0244, 0.6859, 0.1468, 0.8692, 0.9059,
        0.5739, 0.5554, 0.9353, 0.6970, 0.8855, 0.1646, 0.8709, 0.8433, 0.8853,
        0.0920, 0.4631, 0.9860, 0.0833, 0.9052, 0.9459, 0.0996, 0.0013, 0.8619,
        0.8281, 0.2770, 0.0483, 0.1396, 0.8745, 0.1682, 0.6226, 0.8038, 0.5462,
        0.4253, 0.2071, 0.0231, 0.6860, 

In [5]:
tensor_fp32_to_fp16 = tensor_fp32.to(dtype=torch.bfloat16)
print(tensor_fp32_to_fp16)

tensor([0.3613, 0.8086, 0.0850, 0.3418, 0.2871, 0.9766, 0.2832, 0.6914, 0.8320,
        0.0723, 0.0167, 0.0332, 0.0136, 0.3281, 0.0077, 0.4922, 0.2129, 0.1963,
        0.4492, 0.2021, 0.1855, 0.9336, 0.7461, 0.5938, 0.6367, 0.4297, 0.1187,
        0.2480, 0.7734, 0.7383, 0.0569, 0.6016, 0.3477, 0.5859, 0.1001, 0.2041,
        0.1562, 0.2578, 0.1484, 0.4414, 0.7344, 0.1328, 0.2051, 0.7461, 0.6133,
        0.3867, 0.6289, 0.6211, 0.4414, 0.4785, 0.5508, 0.2969, 0.3652, 0.3496,
        0.0581, 0.5352, 0.5664, 0.3770, 0.7773, 0.2207, 0.8555, 0.7266, 0.9062,
        0.6758, 0.7812, 0.8828, 0.6328, 0.0981, 0.1484, 0.9180, 0.9883, 0.0742,
        0.5234, 0.1963, 0.2832, 0.9141, 0.0244, 0.6875, 0.1465, 0.8711, 0.9062,
        0.5742, 0.5547, 0.9336, 0.6953, 0.8867, 0.1650, 0.8711, 0.8438, 0.8867,
        0.0918, 0.4629, 0.9844, 0.0835, 0.9062, 0.9453, 0.0996, 0.0013, 0.8633,
        0.8281, 0.2773, 0.0483, 0.1396, 0.8750, 0.1680, 0.6211, 0.8047, 0.5469,
        0.4258, 0.2070, 0.0231, 0.6875, 

In [7]:
m_float32 = torch.dot(tensor_fp32, tensor_fp32)
print(m_float32)
m_float16 = torch.dot(tensor_fp32_to_fp16, tensor_fp32_to_fp16)
print(m_float16)

tensor(329.7125)
tensor(330., dtype=torch.bfloat16)


In [9]:
!pip install transformers

In [11]:
pip install 'accelerate>=0.26.0'

Note: you may need to restart the kernel to use updated packages.


In [13]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import os
os.environ["HF_TOKEN"] = "HF_TOKEN"
model_name = "EleutherAI/pythia-410m"
model = AutoModelForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True)
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [15]:
print(model.gpt_neox)

GPTNeoXModel(
  (embed_in): Embedding(50304, 1024)
  (emb_dropout): Dropout(p=0.0, inplace=False)
  (layers): ModuleList(
    (0-23): 24 x GPTNeoXLayer(
      (input_layernorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (post_attention_layernorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (post_attention_dropout): Dropout(p=0.0, inplace=False)
      (post_mlp_dropout): Dropout(p=0.0, inplace=False)
      (attention): GPTNeoXSdpaAttention(
        (rotary_emb): GPTNeoXRotaryEmbedding()
        (query_key_value): Linear(in_features=1024, out_features=3072, bias=True)
        (dense): Linear(in_features=1024, out_features=1024, bias=True)
        (attention_dropout): Dropout(p=0.0, inplace=False)
      )
      (mlp): GPTNeoXMLP(
        (dense_h_to_4h): Linear(in_features=1024, out_features=4096, bias=True)
        (dense_4h_to_h): Linear(in_features=4096, out_features=1024, bias=True)
        (act): GELUActivation()
      )
    )
  )
  (final_layer_n

In [17]:
text = "Once upon a time, there was a"
inputs = tokenizer(text, return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=10)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
print(inputs)
print(outputs)

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.


Once upon a time, there was a man who was a great
and powerful king.
{'input_ids': tensor([[10758,  2220,   247,   673,    13,   627,   369,   247]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}
tensor([[10758,  2220,   247,   673,    13,   627,   369,   247,   637,   665,
           369,   247,  1270,   187,   395,  6422,  6963,    15]])


In [19]:
print(model.gpt_neox.layers[0].attention.dense.weight)

Parameter containing:
tensor([[ 0.0061, -0.0016, -0.0068,  ..., -0.0062,  0.0138,  0.0222],
        [ 0.0077,  0.0157, -0.0090,  ...,  0.0013, -0.0132,  0.0109],
        [-0.0330,  0.0008,  0.0281,  ...,  0.0026,  0.0456, -0.0077],
        ...,
        [-0.0105,  0.0091, -0.0137,  ..., -0.0046,  0.0371, -0.0077],
        [-0.0063,  0.0035,  0.0147,  ...,  0.0220,  0.0158,  0.0224],
        [-0.0299,  0.0129,  0.0208,  ..., -0.0040, -0.0065,  0.0122]],
       requires_grad=True)


In [21]:
!pip install quanto

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [23]:
from quanto import quantize, freeze, qint8
quantize(model, weights=qint8, activations=None)

In [25]:
print(model)

GPTNeoXForCausalLM(
  (gpt_neox): GPTNeoXModel(
    (embed_in): Embedding(50304, 1024)
    (emb_dropout): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0-23): 24 x GPTNeoXLayer(
        (input_layernorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (post_attention_layernorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (post_attention_dropout): Dropout(p=0.0, inplace=False)
        (post_mlp_dropout): Dropout(p=0.0, inplace=False)
        (attention): GPTNeoXSdpaAttention(
          (rotary_emb): GPTNeoXRotaryEmbedding()
          (query_key_value): QLinear(in_features=1024, out_features=3072, bias=True)
          (dense): QLinear(in_features=1024, out_features=1024, bias=True)
          (attention_dropout): Dropout(p=0.0, inplace=False)
        )
        (mlp): GPTNeoXMLP(
          (dense_h_to_4h): QLinear(in_features=1024, out_features=4096, bias=True)
          (dense_4h_to_h): QLinear(in_features=4096, out_features=1024, bias=

In [27]:
print(model.gpt_neox.layers[0].attention.dense.weight)

Parameter containing:
tensor([[ 0.0061, -0.0016, -0.0068,  ..., -0.0062,  0.0138,  0.0222],
        [ 0.0077,  0.0157, -0.0090,  ...,  0.0013, -0.0132,  0.0109],
        [-0.0330,  0.0008,  0.0281,  ...,  0.0026,  0.0456, -0.0077],
        ...,
        [-0.0105,  0.0091, -0.0137,  ..., -0.0046,  0.0371, -0.0077],
        [-0.0063,  0.0035,  0.0147,  ...,  0.0220,  0.0158,  0.0224],
        [-0.0299,  0.0129,  0.0208,  ..., -0.0040, -0.0065,  0.0122]],
       requires_grad=True)


In [29]:
freeze(model)

In [31]:
print(model.gpt_neox.layers[0].attention.dense.weight)

QBytesTensor(tensor([[ 12,  -3, -14,  ..., -12,  28,  45],
        [ 18,  37, -21,  ...,   3, -31,  26],
        [-75,   2,  64,  ...,   6, 104, -18],
        ...,
        [-25,  22, -33,  ..., -11,  89, -19],
        [-14,   8,  33,  ...,  49,  35,  50],
        [-56,  24,  39,  ...,  -8, -12,  23]], dtype=torch.int8), scale=tensor([[0.0005],
        [0.0004],
        [0.0004],
        ...,
        [0.0004],
        [0.0004],
        [0.0005]]), dtype=torch.float32)


In [53]:
text1 = """
    Consider the below context and answer accordingly.
    Lions are found in Gir, Gujarat. Those lions are orange and that's why they known as Kesari. Their population is around 1 lacs.

    Where Kesari found and who are they?
"""
inputs1 = tokenizer(text1, return_tensors="pt")
outputs1 = model.generate(**inputs1, max_new_tokens=10)
print(tokenizer.decode(outputs1[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.



    Consider the below context and answer accordingly.
    Lions are found in Gir, Gujarat. Those lions are orange and that's why they known as Kesari. Their population is around 1 lacs.

    Where Kesari found and who are they?
    Kesari is a lion in Gir,
